import { Document } from "mongoose";
export type themeType = "light" | "dark" | "system";
export interface MenuItem {
  name: string;
  image: string;
  category: string;
  count: boolean;
  sizes: Record<
    string,
    {
      price: number;
      quantity: number;
    }
  >;
}
export interface BillContentType {
  name: string;
  quantity: number;
  cost: number;
  size: string;
}
export interface BillType {
  totalAmount: number;
  totalDishes: number;
  tableId: string;
  paymentMethod: "cash" | "upi";
  credited: boolean;
  billcontent: BillContentType[];
  discount: number;
  customerName: string;
  amountPayable: number;
  timestamp: number;
  tablestamp: number;
}
export interface BillModelType extends Document, BillType {}

export interface tableType {
  tableId: string;
  totalAmount: number;
  totalDishes: number;
  OrderDetails: MenuItem[];
  tablestamp: number;
  createdAt?: Date; // Auto-generated by Mongoose
  updatedAt?: Date; // Auto-updated by Mongoose
}
export interface OrdersState {
  tables: Record<string, tableType>;
}

// Define the interface for DishSize
interface IDishSize {
  price: number;
  quantity: number;
}

// Define the interface for Dish
export interface IDish extends Document {
  name: string;
  image: string;
  sizes: {
    quarter: IDishSize;
    half: IDishSize;
    full: IDishSize;
  };
  category: string;
  count: boolean;
}
// Define the interface for a Table document
export interface ITable extends Document, tableType {}

export interface toastType {
  message: string;
  status: "success" | "error";
  timestamp: number;
}
